import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const { mutateAsync: mutateCar } = api.car.get.useMutation();

  const handleSearch = async () => {
    await mutateCar(
      {
        license_plate: "7115056", // get from state
      },
      {
        onSuccess(data) {
          console.log(data);
        },
      }
    );
  };

  return (
    <>
      {/* <Head>
         <title>Create T3 App</title>
         <meta name="description" content="Generated by create-t3-app" />
         <link rel="icon" href="/favicon.ico" />
       </Head> */}
      <button onClick={() => void handleSearch()}></button>
    </>
  );
};

export default Home;
